### ISSUE TITLE
Lecture Videos no longer available

### ISSUE THREAD

**Issue by artysidorenko** [NatashaTheRobot/Stanford-CS-106A#4]
FYI - the lecture videos are no longer available for this course.

BUT you can access videos for the same course from a different year (2008) via iTunes university for free. The subject matter appears to be the same so is compatible with the handouts/assignments provided here.

**Comment by MattKleinsmith** [comment]
The lecture videos are available now. Here's a YouTube playlist: https://www.youtube.com/playlist?list=PL84A56BC7F4A1F852
